apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-myk8skv
spec:
  provider: azure
  secretObjects:
  - secretName: test-secret
    data:
    - key: key
      objectName: ExamplePassword
    type: Opaque
  parameters:
    usePodIdentity: "true"                                      
    useVMManagedIdentity: "false"                               
    userAssignedIdentityID: ""                                                                                                
    keyvaultName: "myk8skv"                                                                
    cloudName: ""                                               
    objects:  |
      array:
        - |
          objectName: ExamplePassword                              
          objectType: secret                                    
          objectVersion: ""                                     
    resourceGroup: "aks2akvrg"                      
    subscriptionId: "<subscription id>"      
    tenantId: "<tenant id>"    
kind: SecretProviderClass
metadata:
  name: spc-myk8skv
spec:
  provider: azure
  secretObjects:
  - secretName: test-secret
    data:
    - key: key
      objectName: ExamplePassword
    type: Opaque
  parameters:
    usePodIdentity: "true"                                      
    useVMManagedIdentity: "false"                               
    userAssignedIdentityID: ""                                                                                                
    keyvaultName: "myk8skv"                                                                
    cloudName: ""                                               
    objects:  |
      array:
        - |
          objectName: ExamplePassword                              
          objectType: secret                                    
          objectVersion: ""                                     
    resourceGroup: "aks2akvrg"                      
    subscriptionId: "<subscription id>"      
    tenantId: "<tenant id>"    